#!/usr/bin/env python3
"""Small entry point for Linux Workbench commands."""

import sys

sys.dont_write_bytecode = True

from workbenchlib.cli import main


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
